on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: "5.3.0"
      - uses: actions/checkout@v2
      - run: swift build
      - run: swift test
