on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    strategy:
      fail-fast: true
      matrix:
        swift: ["5.5", "5.6"]

    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v2
      - run: swift build
      - run: swift test
